server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    username: rabbit
    password: qwesda
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 2

springdoc:
  api-docs:
    path: /service/api-docs
  swagger-ui:
    path: /service/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health" ]

scrape_configs:
  - job_name: 'service-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.21.0.1:8080'] # gateway IP from `docker-compose.yaml` network gateway IP address, only for dev purposes